const interviewQuestions = [
  {
    id: "standing",
    step: "01",
    title: "我现在站在哪里？",
    tip: "每个选择都有现实边界，先看看我现在站在哪里。",
    type: "fields",
    fields: [
      { key: "province", label: "所在省份", summaryLabel: "省份", placeholder: "例如：广东" },
      { key: "subjects", label: "选科组合", summaryLabel: "选科", placeholder: "例如：物理、化学、生物" },
      { key: "score", label: "预估分数", summaryLabel: "分数", placeholder: "可空", inputType: "number" },
      { key: "rank", label: "预估位次", summaryLabel: "位次", placeholder: "可空", inputType: "number" },
    ],
  },
  {
    id: "future",
    step: "02",
    title: "我对未来有什么初步想法？",
    tip: "不确定也没关系，很多人是在填志愿时才第一次认真思考这些问题。",
    type: "fields",
    fields: [
      { key: "targetSchool", label: "想去的学校", summaryLabel: "目标学校", placeholder: "可空，也可以写“不知道”" },
      { key: "targetMajor", label: "想学的专业", summaryLabel: "目标专业", placeholder: "可空，也可以写“没想好”" },
      { key: "targetCity", label: "想去的城市", summaryLabel: "目标城市", placeholder: "可空，也可以写“暂未考虑”" },
    ],
  },
  {
    id: "values",
    step: "03",
    title: "我更在意什么？",
    tip: "可以多选。先不用排序，系统会根据你的整体回答做提炼。",
    type: "multi",
    options: ["收入", "稳定", "兴趣", "城市机会", "工作自由度", "成长空间", "社会价值", "家庭期待", "创业可能", "国际化机会"],
    openQuestion: "还有什么你很在意，但选项里没有完全说出来？",
    placeholder: "也可以写下为什么它对你重要。",
  },
  {
    id: "concerns",
    step: "04",
    title: "我最担心什么？",
    tip: "可以多选。担心不是软弱，它通常是在提醒你看见选择成本。",
    type: "multi",
    options: ["选错专业", "毕业找不到工作", "收入太低", "行业衰落", "学不会", "父母反对", "留在小城市", "未来后悔"],
    openQuestion: "如果把这种担心说得更具体，它是什么？",
    placeholder: "例如：担心努力很多年后仍然没有方向。",
  },
  {
    id: "tradeoff",
    step: "05",
    title: "当理想与现实发生冲突时",
    tip: "0 表示完全理想导向，100 表示完全现实导向。",
    type: "slider",
    min: 0,
    max: 100,
    defaultValue: 50,
    leftLabel: "理想优先",
    rightLabel: "现实优先",
    openQuestion: "为什么你会把自己放在这个位置？",
    placeholder: "可以写一个最近真实纠结过的选择。",
  },
  {
    id: "university",
    step: "06",
    title: "我希望大学带给我什么？",
    tip: "可以多选，也可以留下一句话给四年后的自己。",
    type: "mixed",
    options: ["好工作", "专业能力", "更大的世界", "更多朋友", "探索兴趣", "创业机会", "出国深造", "改变命运"],
    openQuestion: "四年后的我，会希望现在的我记住什么？",
    placeholder: "写给现在的自己，长短都可以。",
  },
];

module.exports = interviewQuestions;
